
language: r
warnings_are_errors: true
sudo: required

r_binary_packages:
 - rjags

r_github_packages:
 - poissonconsulting/tulip
 - poissonconsulting/datalist
 - poissonconsulting/juggler
 - poissonconsulting/jaggernaut
 - poissonconsulting/mwstdatr
